### ISSUE TITLE
Utterances returning no intent: breaking the script

### ISSUE THREAD

**Issue by aatakan** [ammardodin/conversation-cross-validation#3]
Traceback (most recent call last):
  File "conversation_cv.py", line 128, in <module>
    print(run_cross_validation(folds, data))
  File "conversation_cv.py", line 103, in run_cross_validation
    top_label = res['intents'][0]['intent']
IndexError: list index out of range

I keep receiving the above error and it seems to happen at varying times. I am printing out the res variable each time and it looks like the problem is that the intent is not returned in the response.

**Comment by ammardodin** [comment]
@aatakan The issue is that the `res['intents']` is empty in the response when the service thinks an utterance is irrelevant/off-topic. I'll update the script shortly to ignore that for now.

**Comment by aatakan** [comment]
ah cool! ok, thanks. also worth noting that the new Watson Assistant API is available now so maybe you can update it to include the latest version of the API too?
